version: '3.8'

services:
  # База данных MongoDB
  mongo:
    image: mongo:4.4
    container_name: telegram-shop-mongo
    restart: always
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-password}
    ports:
      - "27017:27017"
    networks:
      - app-network

  # Бэкенд Node.js
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    container_name: telegram-shop-backend
    restart: always
    depends_on:
      - mongo
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGODB_URI=mongodb://${MONGO_ROOT_USER:-admin}:${MONGO_ROOT_PASSWORD:-password}@mongo:27017/telegram-shop?authSource=admin
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - ADMIN_SECRET_CODE=${ADMIN_SECRET_CODE}
      - YANDEX_DISK_TOKEN=${YANDEX_DISK_TOKEN}
      - YANDEX_DISK_FOLDER=${YANDEX_DISK_FOLDER:-telegram-shop}
      - YOOMONEY_WALLET=${YOOMONEY_WALLET}
      - YOOMONEY_SECRET_KEY=${YOOMONEY_SECRET_KEY}
      - JWT_SECRET=${JWT_SECRET:-your_jwt_secret_key}
      - JWT_EXPIRATION=${JWT_EXPIRATION:-7d}
      - CORS_ORIGIN=${CORS_ORIGIN:-*}
    volumes:
      - ../:/app
      - /app/node_modules
    networks:
      - app-network

  # Фронтенд React
  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
    container_name: telegram-shop-frontend
    restart: always
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=/api
    volumes:
      - ../client:/app
      - /app/node_modules
      - react-build:/app/build
    networks:
      - app-network

  # Nginx для проксирования запросов и раздачи статики
  nginx:
    image: nginx:1.21-alpine
    container_name: telegram-shop-nginx
    restart: always
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - react-build:/usr/share/nginx/html
      - ./ssl:/etc/nginx/ssl
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
  react-build:
