FROM node:16-alpine

WORKDIR /app

# Копируем package.json и package-lock.json для установки зависимостей
COPY package*.json ./

# Устанавливаем зависимости
RUN npm ci --only=production

# Копируем исходный код
COPY . .

# Создаем директорию для логов
RUN mkdir -p /app/logs

# Открываем порт, на котором работает приложение
EXPOSE 3000

# Запускаем сервер
CMD ["node", "server.js"]
